require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree-config")
require("core.plugin_config.catppuccin-config")
require("core.plugin_config.mason")
require("core.plugin_config.lsp_config")
require("core.plugin_config.indent_blankline")
